name: auto_build_release

on:
  schedule:
    - cron: '50 9 * * *' # 每天凌晨1点40分执行

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4

      - run: pnpm install

      - run: pnpm run build

      - id: version
        run: |
          version=$(node -e "import('@gkd-kit/tools').then((m) => m.stdoutGkdVersion());")
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Check for Changes
        id: check_changes
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          if [ -z "$latest_tag" ]; then
            echo "No tags found."
            echo "::set-output name=has_changes::false"
          else
            changes=$(git diff --name-only $latest_tag HEAD -- ./src)
            if [ -z "$changes" ]; then
              echo "No changes detected in ./src"
              echo "::set-output name=has_changes::false"
            else
              echo "Changes detected in ./src:"
              echo "$changes"
              echo "::set-output name=has_changes::true"
            fi
          fi

      - name: Exit if No Changes
        if: steps.check_changes.outputs.has_changes == 'false'
        run: |
          echo "No changes detected. Exiting workflow."
          exit 0

      - name: Determine Version
        id: version
        run: |
          version=$(node -e "import('@gkd-kit/tools').then((m) => m.stdoutGkdVersion());")
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Git Commit
        id: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git add .
          git commit -a -m "chore: v${{ steps.version.outputs.version }}"
        continue-on-error: true

      - name: Git Push
        if: ${{ steps.commit.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Create Release
        if: ${{ steps.commit.outcome == 'success' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body_path: ./dist/CHANGELOG.md

      - name: Publish Package
        if: ${{ steps.commit.outcome == 'success' && secrets.NPM_TOKEN != '' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          node -e "import('@gkd-kit/tools').then((m) => m.updatePkgVersion());"
          pnpm publish --no-git-checks
          node -e "import('@gkd-kit/tools').then((m) => m.syncNpmmirror());"
